### ISSUE TITLE
show vectors instead of lines

### ISSUE THREAD

**Issue by CD3** [CD3/VectorFieldPlot#2]

**Comment by Geek3wiki** [comment]
Showing vectors instead of field lines is actually a lot simpler. Many programs can readily do that, see for example https://commons.wikimedia.org/wiki/File:Stokes_aether_drag.svg from Matplotlib or https://commons.wikimedia.org/wiki/File:Uniform_curl.svg from Mathematica.

**Comment by CD3** [comment]
Thanks. I actually implemented this shortly after opening the issue and then never closed it.
